name: fixme
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  intl_phone_field: ^3.2.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_database: ^11.3.7
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.2.7
  fluttertoast: ^8.2.12
  image_picker: ^1.0.7
  intl: ^0.19.0
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.3
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  lottie: ^3.1.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  google_mlkit_face_detection: ^0.9.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/fixme-logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/images/
    - assets/animations/
    - assets/images/service_center/
    - .env
